### ISSUE TITLE
More detailed YAML

### ISSUE THREAD

**Issue by thatvideoshopguy** [thatvideoshopguy/spamalot#1]
The YAML file should group tasks into distinct chapters and provide a brief description for each chapter. An example is provided below:

```yaml
exercises:
  basics:
    title: Basics
    description: Learn the basics of the language
    exercises:
      - exercise1
      - exercise2
      - exercise3
```

In this format, the basics chapter is defined with a title and description fields, followed by a list of exercises. This way, it is easy to organise and describe the content of each chapter in the YAML file.
